---
name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install libmpv-dev libglib2.0-dev libavformat-dev pkg-config
      - name: Install Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: "0.14.1"
      - name: Setup dirs
        run: make setup
      - name: Build Zig
        run: |
          make build-zig
          echo "Zig build completed"
      # - name: Verify zig build output
      #   run: |
      #     echo "Checking Zig build directory..."
      #     ls -la build/zig-out/lib/ || echo "Zig lib directory not found"
      #     if [ -f "build/zig-out/lib/libmpris.so" ]; then
      #       echo "Zig binary found:"
      #       file build/zig-out/lib/libmpris.so
      #       ls -la build/zig-out/lib/libmpris.so
      #     else
      #       echo "ERROR: Zig binary not found at expected path"
      #       echo "Contents of build directory:"
      #       find build/ -name "*.so" -type f 2>/dev/null || echo "No .so files found in build/"
      #       exit 1
      #     fi
      - name: Build c
        run: |
          make build-c
          echo "C build completed"
      # - name: Verify c build output
      #   run: |
      #     echo "Checking C build directory..."
      #     ls -la build/c-out/lib/ || echo "C lib directory not found"
      #     if [ -f "build/c-out/lib/libmpris.so" ]; then
      #       echo "C binary found:"
      #       file build/c-out/lib/libmpris.so
      #       ls -la build/c-out/lib/libmpris.so
      #     else
      #       echo "ERROR: C binary not found at expected path"
      #       echo "Contents of build directory:"
      #       find build/ -name "*.so" -type f 2>/dev/null || echo "No .so files found in build/"
      #       exit 1
      #     fi
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: libmpris-so
          path: build/zig-out/lib/libmpris.so
          if-no-files-found: error
      - name: Prepare for test
        run: |
          sudo apt install mpv playerctl sound-theme-freedesktop bash dbus xvfb xauth jq socat gawk
      - name: Run tests
        run: |
          make test-c
      - name: Check git files unmodified
        run: |
          git diff --exit-code HEAD
      - name: Check .gitignore matches generated files
        run: |
          ! git ls-files --others --exclude-standard | grep .
      - name: Cleanup generated files
        run: |
          # Clean both make and zig artifacts
          make clean || true
          zig build clean || true
          rm -rf zig-out .zig-cache
      - name: Check cleanup removed generated files
        run: |
          ! git ls-files --others | grep .