---
name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install libmpv-dev libglib2.0-dev libavformat-dev pkg-config
      - name: Install Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: "0.15.1"
      - name: Build c
        run: |
          make build
      - name: Verify c build output
        run: |
          ls -la mpris.so
          file mpris.so
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: mpris-so
          path: mpris.so
          if-no-files-found: error
      - name: Prepare for test
        run: |
          sudo apt install mpv playerctl sound-theme-freedesktop bash dbus xvfb xauth jq socat gawk
      - name: Run tests
        run: |
          make test
      - name: Check git files unmodified
        run: |
          git diff --exit-code HEAD
      - name: Check .gitignore matches generated files
        run: |
          ! git ls-files --others --exclude-standard | grep .
      - name: Cleanup generated files
        run: |
          # Clean both make and zig artifacts
          make clean || true
      - name: Check cleanup removed generated files
        run: |
          ! git ls-files --others | grep .